### ISSUE TITLE
WDL compatibility with Azure

### ISSUE THREAD

**Issue by vsmalladi** [lilab-bcb/cumulus#366]
See compatibility notes here:
https://github.com/microsoft/CromwellOnAzure/blob/master/docs/change-existing-WDL-for-Azure.md/#How-to-modify-an-existing-WDL-file-to-run-on-Cromwell-on-Azure

Mostly focused on making sure some of the runtime block items are specified in compatible ways (ie, that memory and disk always have units attached) and that we add a maxRetries synonym for wherever we specify preemptible. We might already be compatible, it's just worth going through and double checking...

**Comment by yihming** [comment]
@vsmalladi Thanks for checking this compatibility with Azure. However, our doesn't have any deployment on Azure, but only AWS and GCP. So we won't be able to test our workflows for Azure. 

To move forward, I may follow the this note to add the corresponding runtime attributes, since it will be ignored for other cloud backends. But I'll have to leave it for Azure users to test.

**Comment by vsmalladi** [comment]
@yihming should i make the changes to make Azure compatible and provide a PR?

**Comment by yihming** [comment]
@vsmalladi If possible, we'd appreciate your help. You don't need to modify all the WDLs as that would be too much. You may just change the workflows you use frequently, and I can follow your changes for the rest of them.

**Comment by yihming** [comment]
@vsmalladi We've heard that Azure is collaborating with Broad Institute on bringing Azure to Terra platform. As our team is also closely collaborating with Broad, maybe we could have a meeting about how to enable our workflows work for Azure and maintain them. Does it sound feasible?
